parameters:
    class.guzzle.response: Guzzle\Http\Message\Response

services:
    guzzle.twitter.client:
        class: Guzzle\Http\Client
        arguments: ['https://api.twitter.com/1.1']
        calls:
            - [addSubscriber, [@guzzle.twitter.oauthplugin]]

    guzzle.twitter.oauthplugin:
        class: Guzzle\Plugin\Oauth\OauthPlugin
        arguments:
            config:
                consumer_key: %twitter_consumer_key%
                consumer_secret: %twitter_consumer_secret%
                token: %twitter_token%
                token_secret: %twitter_token_secret%
