<?php

namespace Johanlopes\CoreBundle\Entity;

use Symfony\Component\Finder\Finder;
use Johanlopes\CoreBundle\Entity\Project;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository
{
    protected $finder;

    public function __construct($dataPath)
    {
        $this->finder = new Finder();
        $this->finder->in($dataPath)->files();
    }

    /**
     * Find project by slug
     *
     * @param $slug
     * @return Johanlopes\CoreBundle\Entity\Project
     */
    public function find($slug)
    {
        $finder = clone($this->finder);
        $finder->name($slug . ".json");

        if ($finder->count() > 0) {
            $iterator = $finder->getIterator();
            $iterator->rewind();
            $file = $iterator->current();

            return $this->jsonToProject($file->getContents());
        }

        return null;
    }

    /**
     * Find all projects
     *
     * @retur array
     */
    public function findAll()
    {
        $finder = clone($this->finder);
        $finder->name("*.json");

        $projects = array();

        foreach($finder as $file) {
            $projects[] = $this->jsonToProject($file->getContents());
        }

        return $projects;
    }

    private function jsonToProject($json)
    {
        $infos = json_decode($json, true);

        $project = new Project();
        $project->setName($infos['name']);
        $project->setResume($infos['resume']);
        $project->setTechnology($infos['technology']);
        $project->setUrl($infos['url']);
        $project->setImage($infos['image']);
        $project->setRank($infos['rank']);
        $project->setSlug($infos['slug']);

        return $project;
    }
}
