<?php

namespace Johanlopes\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    /**
     * Find projects sorted
     *
     * @return ArrayCollection
     */
    public function findAllSorted()
    {
        $query = $this->createQueryBuilder('p')
        ->orderBy('p.rank', 'ASC')
        ->getQuery();

        return $query->getResult();
    }

    /**
     * Incrémentation de la position
     * @param Project $object
     */
    public function moveDown(Project $object)
    {
        $position = $object->getRank();

        if ($position < $this->getFinalPosition()) {
            $object->setRank($position + 1);
            $this->_em->persist($object);
            $this->_em->flush();
            $this->_em->clear();
        }
    }

    /**
     * Décrémentation de la position
     * @param Project $object
     */
    public function moveUp(Project $object)
    {
        $position = $object->getRank();

        if ($position > 1) {
            $object->setRank($position - 1);
            $this->_em->persist($object);
            $this->_em->flush();
            $this->_em->clear();
        }
    }

    /**
     * Get final position
     *
     * @return integer
     */
    public function getFinalPosition()
    {
        $q = $this->createQueryBuilder('c')
            ->select('c.rank')
            ->orderBy('c.rank', 'desc')
            ->setMaxResults(1);

        $last = $q->getQuery()->getSingleResult();
        $finalPosition = $last ? $last['rank'] : 1;

        return (int) $finalPosition;
    }
}
